# Generated by Django 4.2.2 on 2023-09-05 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movie_recommendation_api.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_role_careers"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=256, null=True)),
                ("last_name", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        default="user_profile_image/blank-profile-image.png",
                        upload_to=movie_recommendation_api.users.models.user_profile_image_file_path,
                    ),
                ),
                ("bio", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "favorite_genres",
                    models.ManyToManyField(blank=True, to="movie.genre"),
                ),
                ("ratings", models.ManyToManyField(blank=True, to="movie.rating")),
                ("reviews", models.ManyToManyField(blank=True, to="movie.review")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("watchlist", models.ManyToManyField(blank=True, to="movie.movie")),
            ],
        ),
    ]
