# Generated by Django 4.2.2 on 2023-06-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_randommodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomModel',
        ),
    ]
