# Generated by Django 4.2.2 on 2023-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="ratings",
            field=models.ManyToManyField(
                blank=True, related_name="rated_movies", to="movie.rating"
            ),
        ),
    ]
