# Generated by Django 4.2.2 on 2023-08-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_alter_movie_ratings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="castcrew",
            name="career",
        ),
        migrations.AlterField(
            model_name="movie",
            name="cast_crew",
            field=models.ManyToManyField(through="movie.Role", to="movie.castcrew"),
        ),
        migrations.AddField(
            model_name="castcrew",
            name="careers",
            field=models.ManyToManyField(
                related_name="cast_crew_members", to="movie.career"
            ),
        ),
    ]
