# Generated by Django 4.2.2 on 2023-08-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_career_remove_castcrew_career_alter_movie_cast_crew_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="careers",
            field=models.ManyToManyField(related_name="roles", to="movie.career"),
        ),
    ]
