# Generated by Django 4.2.2 on 2023-11-13 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0005_review_slug_review_spoilers_review_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="ratings",
        ),
    ]
