# Generated by Django 4.2.2 on 2023-07-09 14:53

import django.core.validators
from django.db import migrations, models
import movie_recommendation_api.movie.validators


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0005_alter_review_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(
                max_length=512,
                validators=[
                    movie_recommendation_api.movie.validators.validate_review_content,
                    django.core.validators.MaxLengthValidator(
                        512, "Content exceeds the maximum allowed length."
                    ),
                ],
            ),
        ),
    ]
