name: Checks

on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Test-Lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build env File
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > ./env
      - name: Test
        run: docker-compose run --rm backend sh -c "python manage.py wait_for_db && pytest"
      - name: Lint
        run: docker-compose run --rm backend sh -c "flake8"
